export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

export SPARK_HOME=${SPARK_HOME:-/opt/spark}

# EXTRA SPARK + HADOOP VARS
export HADOOP_HOME=${HADOOP_HOME:-/opt/hadoop}
export HADOOP_LIBRARY_PATH="${HADOOP_LIBRARY_PATH}:${HADOOP_HOME}/lib/native"

export SPARK_DIST_CLASSPATH=$(/opt/hadoop/bin/hadoop classpath)
export SPARK_LIBRARY_PATH="${SPARK_LIBRARY_PATH}:${HADOOP_LIBRARY_PATH}"
export SPARK_EXTRA_CLASSPATH="${SPARK_EXTRA_CLASSPATH}:${SPARK_DIST_CLASSPATH}"
export SPARK_DAEMON_CLASSPATH="${SPARK_DAEMON_CLASSPATH}:${HADOOP_HOME}/share/hadoop/tools/lib/*"
export SPARK_LIBRARY_PATH=$SPARK_LIBRARY_PATH:${HADOOP_HOME}/lib/native

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HADOOP_LIBRARY_PATH}"
